/* ISC license. */

/* Generated by: ./configure --prefix=/opt/ska --with-include=/opt/ska/include/ --with-lib=/opt/ska/lib/skalibs/ --with-dynlib=/opt/ska/lib/ --enable-static-libc */

#ifndef SOCKLOG_CONFIG_H
#define SOCKLOG_CONFIG_H

#define SOCKLOG_VERSION "1.2.0"
#define SOCKLOG_BINPREFIX ""
#define SOCKLOG_EXTBINPREFIX ""
#define SOCKLOG_LIBEXECPREFIX "/opt/ska/libexec/"

#endif
